export const TASK_SEED = [
  {
    taskId: 1,
    taskName: "Aprendre React",
    taskCategory: "Estudis",
    taskDueDate: "2026-01-10",
    taskPriority: "alta",
    taskImportant: true,
    taskDescription: "Repasar useState, useEffect i components.",
    completed: false,
  },
  {
    taskId: 2,
    taskName: "Fer la compra",
    taskCategory: "Casa",
    taskDueDate: "2026-01-05",
    taskPriority: "mitjana",
    taskImportant: false,
    taskDescription: "Llet, pa, ous i fruita.",
    completed: false,
  },
  {
    taskId: 3,
    taskName: "Enviar CVs",
    taskCategory: "Feina",
    taskDueDate: "2026-01-15",
    taskPriority: "alta",
    taskImportant: true,
    taskDescription: "Aplicar a ofertes de frontend junior.",
    completed: true,
  },
  {
    taskId: 4,
    taskName: "Sortir a caminar",
    taskCategory: "Personal",
    taskDueDate: "2026-01-03",
    taskPriority: "baixa",
    taskImportant: false,
    taskDescription: "Desconnectar una estona.",
    completed: true,
  },
];
